
services:
  mariadb:
    build: ./srcs/MariaDB
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SECOND_USER: ${MYSQL_SECOND_USER}
      MYSQL_SECOND_PASSWORD: ${MYSQL_SECOND_PASSWORD}
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql

  php:
    build: ./srcs/PHP
    container_name: php
    restart: always
    environment:
      MARIADB_HOST: mariadb:3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','https://jramos-a.42.fr');
        define('WP_SITEURL','https://jramos-a.42.fr');
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb

  nginx:
    build: ./srcs/NGINX
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - php

  redis:
    build: ./srcs/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception
    depends_on:
      - php

  ftp:
    build: ./srcs/bonus/ftp
    container_name: ftp
    restart: always
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - inception
    volumes:
      - wp_data:/home/ftpuser:rw
    environment:
      FTP_USER: ftpuser
      FTP_PASS: ftppass

  website:
    build: ./srcs/bonus/website
    container_name: website
    restart: always
    ports:
      - "8080:80"
    networks:
      - inception

  adminer:
    build: ./srcs/bonus/adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:80"
    networks:
      - inception
    depends_on:
      - mariadb

  portainer:
    build: ./srcs/bonus/portainer
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    networks:
      - inception
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jramos-a/data/db
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jramos-a/data/wp
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jramos-a/data/portainer
